### ISSUE TITLE
Cinnamon error message after update to 2024.01.16

### ISSUE THREAD

**Issue by Mar-tux** [raphaelquintao/QRedshiftCinnamon#66]
Hello Raphael,
after the last update a message appear which says that cinnamon is not able to start an applet. 
In Looking Glass i found the folowing error message:

error t=2024-01-16T11:08:59Z 
[qredshift@quintao]: Meta.is_wayland_compositor is not a function
[qredshift@quintao]: Failed to load applet: qredshift@quintao/14
error t=2024-01-16T11:08:59Z 
[qredshift@quintao]: Applet qredshift@quintao: Could not create applet object.
[qredshift@quintao]: Error importing applet.js from qredshift@quintao

QRedshift seems to work normal, but on every system startup the message mentioned above is shown. 

Greetings 

Markus

**Comment by vilqvilq** [comment]
I confirm same error, 1.7.5 works without any issue

Mint 20.3 Cin 5.2.7

**Comment by ChrisHonegger** [comment]
Confirm the same issue with V1.7.6 on Mint 20.3

**Comment by invalidSwitch** [comment]
Issue still present with Version 1.7.6 (2024-04-21 14:56:05)

- System:  Kernel: 5.4.0-177-generic x86_64
- Desktop: Cinnamon 5.2.7
- Distro: Linux Mint 20.3 Una

**Comment by Mar-tux** [comment]
Is there any interest from the developer in removing this error?

Or is the basic idea: Linux Mint 20.3 will be "End of Life" from April 2025 and thus the problem with this error message will also be "solved"?

Is it so difficult to make a query that checks whether the Linux Mint version used supports Wayland at all?

**Comment by ChrisHonegger** [comment]
My workaround is was to manually install V1.7.3 and then block the update for this applet. By this, the annoying notifications during startup are gone. 
As soon is Mint 22 is available, I will update any; Mint 20 will then have done its job for four years without any major problems. That robustness is what keeps me with Linux Mint in the future.

**Comment by Mar-tux** [comment]
@ChrisHoS 
Can you give a short description of how to do this?
I'm not much of a command line person.
That would definitely help other users who come here looking for a solution.

Thanks in advance. :-)

**Comment by ChrisHonegger** [comment]
@Mar-tux:
It should be possible without command line knowledge.
1. take snapshot with Timeshift, in case anything goes wrong
2. go to [QRedshift](https://github.com/linuxmint/cinnamon-spices-applets/tree/master/qredshift%40quintao)
3.  here you can find a) the link to the original repository and b) an instruction where to install it in the documentation under point 2.
4. follow https://github.com/raphaelquintao/QRedshift -> go to releases (on the right hand side of the gitlab page
5. download V1.7.3: open the assets section and download the .zip file
6. expand it to `~/.local/share/cinnamon/applets`; take care that the same folder structure exists as before
7. probably you need to restart cinnamon: `ALT+F2`, then enter `r` and hit enter
8. disable automatic updates for applets

I hope that helps.

**Comment by Mar-tux** [comment]
Yes, it worked! Thank you very much. Finally, that annoying message at startup is gone!

I'm also waiting for Mint 22 - another 4-6 weeks after it's released so that there are no bug surprises.

Linux Mint has been running on my computers since 2016. I've also tried other distros, but I've always come back to Mint.

Thanks again and have a nice weekend. :-)

**Comment by raphaelquintao** [comment]
Will be fixed on version 2.0, that will be released in the following days.
